### ISSUE TITLE
Regex

### ISSUE THREAD

**Issue by niknah** [807502278/ComfyUI_MaskGCT#7]
Regex error (I am using python 3.12)...
models/tts/maskgct/g2p/g2p/english.py:178

I changed the line to the below and it worked...
regex = regex.replace("|", r"\|")

**Comment by 807502278** [comment]
Thank you very much for your reminder : )
I will update it when I have time!

**Comment by 807502278** [comment]
Using this on Python 3.11 will cause g2p to get stuck
It seems that it only applies to>=python3.12,the code has been submitted but I haven't tested it myself
